slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: mapping
    resolution: 0.05
    minimum_travel_distance: 0.3
    minimum_travel_heading: 0.3
    scan_topic: /scan
    base_frame: base_footprint
    odom_frame: odom
    map_frame: map
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    enable_interactive_mode: true
